

Caesar interim, quoniam inopia frumenti premebatur, copias omnis in castra conducit atque praesidio Lepti, Ruspinae, Acyllae relicto, Cispio Aquilaeque classe tradita ut alter Hadrumetum, alter Thapsum mari obsiderent, ipse castris incensis quarta noctis vigilia acie instructa impedimentis in sinistra parte collocatis ex eo loco proficiscitur et pervenit ad oppidum Aggar, quod a Gaetulis saepe
antea oppugnatum summaque vi per ipsos oppidanos erat defensum. Ibi in campo castris unis positis ipse frumentatum circum villas cum parte exercitus profectus magno invento hordei, olei, vini, fici numero, pauco tritici, atque recreato exercitu redit in castra. Scipio interim cognito Caesaris discessu cum universis copiis per iugum Caesarem subsequi coepit atque ab eius castris milia passuum
VI
longe trinis castris dispertitis copiis consedit.


Oppidum erat Zeta, quod aberat a Scipione milia passuum
X
, ad eius regionem et partem castrorum collocatum, a Caesare autem diversum ac remotum, quod erat ab eo longe milia passuum
XIIII
.
Huc Scipio legiones duas frumentandi gratia misit. Quod postquam Caesar ex perfuga cognovit, castris ex campo in collem ac tutiora loca collatis atque ibi praesidio relicto ipse quarta vigilia egressus praeter hostium castra proficiscitur cum copiis et oppidum potitur. Legiones Scipionis comperit longius in agris frumentari et, cum eo contendere conaretur, animadvertit copias hostium his legionibus occurrere suppetias. Quae res eius impetum retardavit. Itaque capto C. Minucio Regino, equite Romano, Scipionis familiarissimo, qui ei oppido praeerat, et P. Atrio, equite Romano de conventu Uticensi, et camelis
XXII
regis abductis, praesidio ibi cum Oppio legato relicto ipse se recipere coepit ad castra.


Cum iam non longe a castris Scipionis abesset, quae eum necesse erat praetergredi, Labienus Afraniusque cum omni equitatu levique armatura ex insidiis adorti agmini eius extremo se offerunt atque ex collibus proximis
exsistunt. Quod postquam Caesar animum advertit, equitibus suis hostium vi oppositis sarcinas legionarios in acervum iubet comportare atque celeriter signa hostibus inferre. Quod postquam coeptum est fieri, primo impetu legionum equitatus et levis armatura hostium nullo negotio loco pulsa et deiecta est de colle. Cum iam Caesar existimasset hostis pulsos deterritosque finem lacessendi facturos et iter coeptum pergere coepisset, iterum celeriter ex proximis collibus erumpunt atque eadem ratione qua ante dixi in Caesaris legionarios impetum faciunt Numidae levisque armatura mirabili velocitate praediti, qui inter equites pugnabant et una pariterque cum equitibus accurrere et refugere consueverant. Cum hoc saepius facerent et proficiscentis Iulianos insequerentur, refugerent instantis, propius non accederent et singulari genere pugnae uterentur equosque
iaculis convulnerare satis esse existimarent, Caesar intellexit nihil aliud eos conari nisi ut se cogerent castra eo loco ponere ubi omnino aquae nihil esset, ut exercitus ieiunus, qui a quarta vigilia
usque ad horam
X
. diei nihil gustasset, ac iumenta siti perirent.


Cum iam ad solis occasum esset, et non totos
C
passus in horis
IIII
esset progressus, equitatu suo propter equorum interitum extremo agmine remoto legiones in vicem ad extremum agmen evocabat. Ita vim hostium placide leniterque procedens per legionarium militem commodius sustinebat. Interim equitum Numidarum copiae dextra sinistraque per collis praecurrere coronaeque in modum cingere multitudine sua Caesaris copias, pars agmen extremum insequi. Caesaris interim non amplius
III
aut
IIII
milites veterani si se convertissent et pila viribus contorta in Numidas infestos coniecissent, amplius duum milium numero ad unum terga vertebant ac rursus ad aciem passim conversis equis se colligebant atque in spatio consequebantur et iacula in legionarios coiciebant. Ita Caesar modo procedendo modo resistendo tardius itinere confecto noctis hora prima omnis suos ad unum in castra incolumis sauciis
X
factis reduxit. Labienus circiter
CCC
amissis, multis vulneratis ac defessis instando omnibus ad suos se recepit. Scipio interim legiones productas cum elephantis, quos ante castra in acie
terroris gratia in conspectu Caesaris collocaverat, reducit in castra.


Caesar contra eiusmodi hostium genera copias suas non ut imperator exercitum veteranum victoremque maximis rebus gestis, sed ut lanista tirones gladiatores condocefacere; quot pedes se reciperent ab hoste et quem ad modum obversi adversariis et in quantulo spatio resisterent, modo procurrerent modo recederent comminarenturque impetum, ac prope quo loco et quem ad modum tela mitterent, praecipere. Mirifice enim hostium levis armatura anxium exercitum nostrum atque sollicitum habebat, quia et equites deterrebat proelium inire propter equorum interitum, quod eos iaculis interficiebat, et legionarium militem defatigabat propter velocitatem: gravis enim armaturae miles simul atque ab eis insectatus constiterat in eosque impetum fecerat, illi veloci cursu periculum facile vitabant.


Quibus ex rebus Caesar vehementer commovebatur quod, quotienscunque proelium
erat commissum, equitatu suo sine legionario milite hostium equitatui levique armaturae eorum nullo modo par esse poterat. Sollicitabatur autem his rebus, quod nondum legiones hostium cognoverat, et quonam modo sustinere se posset ab eorum equitatu levique
armatura, quae erat mirifica, si legiones quoque accessissent. Accedebat etiam haec causa, quod elephantorum magnitudo multitudoque animos militum detinebat in terrore. Cui uni rei tamen invenerat remedium: namque elephantos ex Italia transportari iusserat, quos et miles nosset speciemque et virtutem bestiae cognosceret et cui parti corporis eius telum facile adigi posset, ornatusque ac loricatus cum esset elephas, quae pars corporis eius sine tegmine nuda relinqueretur, ut eo tela coicerentur; praeterea ut iumenta bestiarum odorem, stridorem, spiritum consuetudine capta non reformidarent. Quibus ex rebus largiter erat consecutus: nam et milites bestia manibus pertrectabant earumque tarditatem cognoscebant, equitesque in eos pila praepilata coiciebant, atque in consuetudinem equos patientia bestiarum adduxerat.


Ob has causas quas supra commemoravi sollicitabatur Caesar tardiorque et consideratior erat factus et ex pristina bellandi consuetudine celeritateque excesserat. Neque mirum: copias enim habebat in Gallia bellare consuetas locis campestribus et contra Gallos, homines apertos minimeque insidiosos, qui per virtutem, non per dolum dimicare consuerunt; tum autem erat ei laborandum ut consuefaceret milites hostium dolos, insidias, artificia cognoscere et quid sequi, quid vitare conveniret. Itaque, quo haec
celerius conciperent, dabat operam ut legiones non in uno loco contineret sed per causam frumentandi huc atque illuc rapsaret, ideo quod hostium copias ab se suoque vestigio non discessuras existimabat. Atque post diem tertium productis accuratius suis copiis
sicut instruxerat, propter hostium castra praetergressus aequo loco invitat ad dimicandum. Postquam eos abhorrere videt, reducit sub vesperum legiones in castra.


Legati interim ex oppido Vaga, quod finitimum fuit Zetae, cuius Caesarem potitum esse demonstravimus, veniunt; petunt, obsecrant, ut sibi praesidium mittat; se res compluris quae utiles bello sint sumministraturos. Per id tempus deorum voluntate studioque erga Caesarem transfuga suos civis facit certiores
Iubam regem celeriter cum copiis suis, antequam Caesaris praesidium eo perveniret, ad oppidum accucurrisse atque advenientem multitudine circumdata eo potitum omnibusque eius oppidi incolis ad unum interfectis dedisse oppidum diripiendum delendumque militibus.


Caesar interim lustrato exercitum a. d.
XII
. Kal. April. postero die productis universis copiis progressus ab suis castris milia passuum
V
, a Scipionis circiter duum milium interiecto spatio, in acie constitit. Postquam satis diuque adversarios ab se ad dimicandum invitatos supersedere pugnae animadvertit, reducit copias posteroque die castra movet atque iter ad oppidum Sarsuram, ubi Scipio Numidarum
habuerat praesidium frumentumque comportaverat, ire contendit. Quod ubi Labienus animadvertit, cum equitatu levique armatura agmen eius extremum carpere coepit atque ita lixarum mercatorumque qui plaustris merces portabant interceptis sarcinis addito animo propius audaciusque accedit ad legiones, quod existimabat milites sub onere ac sub sarcinis defatigatos pugnare non posse. Quae res Caesarem non fefellerat: namque expeditos ex singulis legionibus trecenos milites esse iusserat. Itaque eos in equitatum Labieni immissos turmis suorum suppetias mittit. Tum Labienus conversis equis signorum conspectu perterritus turpissime fugere contendit. Multis eius occisis, compluribus vulneratis milites legionarii ad sua se recipiunt signa atque iter inceptum ire coeperunt. Labienus per iugum summum collis dextrorsus procul subsequi non destitit.


Postquam Caesar ad oppidum Sarsuram venit, inspectantibus adversariis interfecto praesidio Scipionis, cum suis auxilium ferre non auderent, fortiter repugnante P. Cornelio, evocato Scipionis, qui ibi praeerat, atque a multitudine circumvento interfectoque oppidum potitur atque ibi frumento exercitui dato postero die ad oppidum Thysdram pervenit; in quo Considius per id tempus fuerat cum grandi praesidio cohorteque sua gladiatorum. Caesar oppidi
natura perspecta aquae inopia ab oppugnatione eius deterritus protinus profectus circiter milia passuum
IIII
ad aquam facit castra atque inde quarta vigilia egressus redit rursus ad ea castra quae ad Aggar habuerat. Idem facit Scipio atque in antique castra copias reducit.


Thabenenses interim, qui sub dicione et potestate Iubae esse consuesserent in extrema eius regni regione maritima locati, interfecto regio praesidio legatos ad Caesarem mittunt, rem a se gestam docent, petunt orantque ut suis fortunis populus Romanus, quod bene meriti essent, auxilium ferret. Caesar eorum consilio probato Marcium Crispum tribus cum cohortibus et sagittariis tormentisque compluribus praesidio Thabenam mittit. Eodem tempore ex legionibus omnibus milites qui aut morbo impediti aut commeatu dato cum signis non potuerant ante transire in Africam ad milia
IIII
, equites
CCCC
, funditores sagittariique mille uno commeatu Caesari occurrerunt. Itaque cum his copiis et omnibus legionibus eductis, sicut erat instructus,
V
milibus passuum ab suis castris, ab Scipionis vero
II
milibus passuum longe constitit in campo.


Erat oppidum infra castra Scipionis nomine Tegea, ubi praesidium equestre circiter
II
milium numero habere consuerat. Eo equitatu dextra sinistra derecto ab oppidi lateribus ipse legiones ex castris
eductas atque in iugo inferiore instructas non longius fere mille passus ab suis muni­tionibus progressus in acie constituit. Postquam diutius in uno loco Scipio commorabatur et tempus diei in otio consumebatur, Caesar equitum turmas suorum iubet in hostium equitatum qui ad oppidum in statione erant facere impressionem levemque armaturam, sagittarios funditoresque eodem summittit. Quod ubi coeptum est fieri et equis concitatis Iuliani impetum fecissent, Pacideius suos equites exporrigere coepit in longitudinem, ut haberent facultatem turmas Iulianas circumfundi et nihilo minus fortissime acerrimeque pugnare. Quod ubi Caesar animadvertit,
CCC
, quos ex legionibus habere expeditos consuerat, ex legione quae proxima ei proelio in acie constiterat iubet equitatui succurrere. Labienus interim suis equitibus auxilia equestria summittere sauciisque ac defatigatis integros recentioribusque viribus equites sumministrare. Postquam equites Iuliani
CCCC
vim hostium ad
IIII
milia numero sustinere non poterant et ab levi armatura Numidarum vulnerabantur minutatimque cedebant, Caesar alteram alam mittit qui satagentibus celeriter occurrerent. Quo facto sui sublati
universi in hostis impressione facta in fugam adversarios dederunt; multis occisis, compluribus vulneratis insecuti per
III
milia passuum usque ad collem hostibus adactis se ad suos recipiunt. Caesar in horam
X
. commoratus, sicut erat instructus, se ad sua castra recepit omnibus incolumibus. In quo proelio Pacideius graviter pilo per cassidem caput ictus compluresque duces ac fortissimus quisque interfecti vulneratique sunt.
